import fs from 'node:fs';
import path from 'node:path';

const read=p=>fs.readFileSync(p,'utf8'), write=(p,s)=>fs.writeFileSync(p,s);
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const dateFor={
  'node-ip-blocked':'2026-08-20','reality-node-blocked':'2026-08-20','transit-ip-blocked':'2026-08-20',
  'xboard-token-multi-ip':'2026-08-20','xboard-free-node-collector':'2026-08-20','xboard-insider-investigation':'2026-08-23'
};
const categoryFor={
  'node-ip-blocked':'Infrastructure','reality-node-blocked':'Infrastructure','transit-ip-blocked':'Infrastructure',
  'xboard-token-multi-ip':'Security','xboard-free-node-collector':'Automation','xboard-insider-investigation':'Security'
};
const tagsFor={Infrastructure:['Network','Reliability'],Security:['XBoard','Evidence'],Automation:['XBoard','Operations']};
const categoryLabel={Infrastructure:'基础设施',Security:'安全审计',Automation:'自动化',Research:'技术研究'};
const tagLabel={Network:'网络架构',Reliability:'可靠性',XBoard:'XBoard',Evidence:'证据分析',Operations:'运营自动化'};
const formatDate=date=>new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric'}).format(new Date(`${date}T00:00:00+08:00`));
const nav=()=>`<header class="site-header"><div class="container nav"><a class="brand" href="/" aria-label="Manguo Labs 首页"><span class="logo" aria-hidden="true">M</span><span>Manguo Labs</span></a><input class="nav-toggle" type="checkbox" id="nav-toggle"><label class="menu-button" for="nav-toggle" role="button" tabindex="0" aria-label="打开导航菜单" aria-controls="primary-navigation" aria-expanded="false"><span></span><span></span><span></span></label><nav id="primary-navigation" aria-label="主导航"><a href="/#solutions">解决方案</a><a href="/articles/">技术研究</a><a href="/node-firewall/">基础设施</a><a class="nav-cta" href="https://t.me/ManguoShop_bot">联系我们</a></nav></div></header>`;
const footer=()=>`<footer class="site-footer"><div class="container footer-grid"><div><a class="brand" href="/"><span class="logo">M</span><span>Manguo Labs</span></a><p>基础设施 · 安全审计 · 自动化</p><p class="footer-note">以证据、可靠架构与清晰边界，帮助技术系统长期稳定运行。</p></div><div><h2>解决方案</h2><a href="/node-firewall/">高可用入口</a><a href="/xboard-security-audit/">XBoard 安全审计</a><a href="/xboard-node-extension/">节点扩展与采集</a></div><div><h2>技术研究</h2><a href="/articles/">全部文章</a><a href="https://t.me/ManguoShop_bot">ManguoShop Bot</a><a href="https://t.me/ManguoShop_bot">联系我们</a></div></div><div class="container copy">© 2026 Manguo Labs · 为可靠运行而构建</div></footer>`;
const icon=(type)=>({infra:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 17V7l8-4 8 4v10l-8 4-8-4Z"/><path d="m4 7 8 4 8-4M12 11v10"/></svg>',security:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 20 6v5c0 5-3.4 8.5-8 10-4.6-1.5-8-5-8-10V6l8-3Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></svg>',automation:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 7h10v10H7z"/><path d="M3 9v6m18-6v6M9 3h6m-6 18h6"/></svg>'})[type];
function head({title,description,canonical,type='website',extra=''}){return `<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${canonical}"><meta property="og:type" content="${type}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta property="og:site_name" content="Manguo Labs"><meta name="theme-color" content="#111827"><link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/assets/style.css">${extra}</head>`}
function document(headData,body){return `<!doctype html><html lang="zh-CN">${head(headData)}<body>${nav()}${body}${footer()}<script src="/assets/site.js" defer></script></body></html>\n`}
function extract(html,regex){const result=html.match(regex)?.[1];if(result!==undefined)return result;if(String(regex).includes('article class="content"'))return html.match(/<article class="prose solution-prose">([\s\S]*?)<\/article>/i)?.[1]||'';return ''}
const solutions=[
  {path:'node-firewall',key:'infra',title:'机场节点 IP / 中转 IP 频繁失效的高可用入口解决方案',description:'机场节点IP、中转IP、入口IP频繁失效？了解面向 XBoard / V2Board 的高可用入口与线路架构优化方案。',eyebrow:'基础设施 / 01',label:'基础设施',summary:'为多段网络路径建立可观测、可替换、可维护的边界。',method:['梳理链路','隔离暴露面','验证变更'],scenes:['入口或中转频繁失效','多线路需要统一维护','需要降低源站直接暴露']},
  {path:'xboard-security-audit',key:'security',title:'XBoard 订阅安全审计与异常账号关联分析',description:'通过 Token、IP、UA 与真实连接 IP 建立 XBoard 订阅安全审计证据链，辅助识别异常共享与账号风险。',eyebrow:'安全审计 / 02',label:'安全审计',summary:'将分散日志转化为可复核的时间线，而不是用单一信号替代判断。',method:['收集证据','关联上下文','保留复核边界'],scenes:['需要排查订阅共享','多数据源记录分散','希望保留人工复核空间']},
  {path:'xboard-node-extension',key:'automation',title:'XBoard 节点扩展与多来源采集系统',description:'支持本地 JSON、远程 API、Clash YAML 与公开线路采集，为 XBoard 用户订阅提供节点处理、过滤与动态扩展能力。',eyebrow:'自动化 / 03',label:'自动化',summary:'用可控的输入、过滤和缓存链路，把多来源节点维护转成可重复的操作。',method:['统一来源','应用规则','安全下发'],scenes:['多来源节点难以维护','需要协议与地区识别','需要按用户状态动态下发']}
];
for(const s of solutions){const p=`${s.path}/index.html`,old=read(p),content=extract(old,/<article class="content">([\s\S]*?)<\/article>/i);const body=`<main><section class="solution-hero"><div class="container split-hero"><div><p class="eyebrow">${s.eyebrow}</p><h1>${s.title}</h1><p class="lead">${s.summary}</p><div class="actions"><a class="btn primary" href="https://t.me/ManguoShop_bot">查看方案</a><a class="btn" href="/articles/">阅读技术研究</a></div></div><div class="architecture-panel ${s.key}"><div class="icon-frame">${icon(s.key)}</div><span>系统概览</span><strong>${s.label}</strong><p>面向真实运营环境的证据驱动设计。</p><div class="signal-line"><i></i><i></i><i></i></div></div></div></section><section class="section"><div class="container capability-row"><div><p class="eyebrow">工作方法</p><h2>从现象到可验证的系统改进。</h2></div><ol>${s.method.map((x,i)=>`<li><b>0${i+1}</b>${x}</li>`).join('')}</ol></div></section><section class="section surface"><div class="container content-layout"><article class="prose solution-prose">${content}</article><aside class="side-rail"><div><span class="eyebrow">适用场景</span><h2>适用场景</h2><ul>${s.scenes.map(x=>`<li>${x}</li>`).join('')}</ul><a class="text-link" href="https://t.me/ManguoShop_bot">前往 ManguoShop <span>→</span></a></div></aside></div></section></main>`;write(p,document({title:`${s.title}｜Manguo Labs`,description:s.description,canonical:`https://manguolabs.com/${s.path}/`,extra:extract(old,/(<script type="application\/ld\+json">[\s\S]*?<\/script>)/i)},body));}
const articleCards=fs.readdirSync('articles',{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>x.name).sort((a,b)=>dateFor[b].localeCompare(dateFor[a]));
const records=[];
for(const slug of articleCards){const p=`articles/${slug}/index.html`,old=read(p),article=extract(old,/<article class="(?:content|prose)[^"]*">([\s\S]*?)<\/article>/i),title=extract(old,/<h1[^>]*>([\s\S]*?)<\/h1>/i).replace(/<[^>]+>/g,''),description=extract(old,/<meta name="description" content="([^"]*)"/i),lead=extract(old,/<p class="lead">([\s\S]*?)<\/p>/i),canonical=extract(old,/<link rel="canonical" href="([^"]+)"/i),intent=extract(old,/<meta name="manguo-canonical-intent" content="([^"]+)"/i),category=categoryFor[slug]||'Research',published=dateFor[slug]||'2026-08-20',tags=tagsFor[category],plain=article.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim(),minutes=Math.max(4,Math.ceil(plain.length/600));
  const jsonLd={"@context":"https://schema.org","@type":"BlogPosting",headline:title,description,author:{"@type":"Organization",name:"Manguo Labs Research"},publisher:{"@type":"Organization",name:"Manguo Labs",url:"https://manguolabs.com/"},datePublished:`${published}T00:00:00+08:00`,dateModified:`${published}T00:00:00+08:00`,mainEntityOfPage:{"@type":"WebPage","@id":canonical},url:canonical,keywords:tags.join(', ')};
  const toc=[...article.matchAll(/<h2[^>]*>([\s\S]*?)<\/h2>/gi)].map((m,i)=>({id:`section-${i+1}`,text:m[1].replace(/<[^>]+>/g,'')}));let indexed=0;const enhanced=article.replace(/<h2([^>]*)>/gi,(_,attrs)=>`<h2${attrs} id="section-${++indexed}">`);
  const meta=`<div class="article-meta"><span>${categoryLabel[category]}</span><i></i><span>Manguo Labs Research</span><i></i><time datetime="${published}">${formatDate(published)}</time><i></i><span>预计阅读 ${minutes} 分钟</span></div>`;
  const tocHtml=`<aside class="toc"><p>本文目录</p><ol>${toc.map(x=>`<li><a href="#${x.id}">${x.text}</a></li>`).join('')}</ol></aside>`;
  const body=`<main><section class="article-hero"><div class="narrow"><p class="breadcrumb"><a href="/articles/">技术研究</a><span>/</span>${categoryLabel[category]}</p><h1>${title}</h1><p class="lead">${lead}</p>${meta}<div class="article-tags">${tags.map(t=>`<span>${tagLabel[t]||t}</span>`).join('')}</div></div></section><section class="article-shell"><div class="article-grid">${tocHtml}<article class="prose article-prose">${enhanced}<div class="author-card"><span class="logo">M</span><div><strong>Manguo Labs Research</strong><p>独立的基础设施、安全审计与自动化技术笔记。</p></div></div><section class="continue"><p class="eyebrow">继续阅读</p><a href="/articles/">浏览全部技术文章 <span>→</span></a></section></article></div></section></main>`;
  const extras=`<meta name="manguo-canonical-intent" content="${intent}"><script type="application/ld+json">${JSON.stringify(jsonLd)}</script>`;write(p,document({title:extract(old,/<title>([^<]+)<\/title>/i)||`${title}｜Manguo Labs`,description,canonical,type:'article',extra:extras},body));records.push({slug,title,description,lead:lead.replace(/<[^>]+>/g,''),category,published,minutes});}
const cards=records.map((r,i)=>`<article class="research-card ${i===0?'featured':''}"><p class="eyebrow">${categoryLabel[r.category]}</p><h2><a href="/articles/${r.slug}/">${r.title}</a></h2><p>${r.lead}</p><div><span>Manguo Labs Research</span><time>${formatDate(r.published)}</time><span>预计阅读 ${r.minutes} 分钟</span></div><a class="text-link" href="/articles/${r.slug}/">阅读全文 <span>→</span></a></article>`).join('');
write('articles/index.html',document({title:'技术研究｜Manguo Labs',description:'Manguo Labs 技术研究：围绕基础设施、安全与自动化的工程化分析。',canonical:'https://manguolabs.com/articles/'},`<main><section class="research-hero"><div class="container"><p class="eyebrow">技术研究</p><h1>技术研究</h1><p class="lead">针对复杂运营环境的可复用工程方法、边界与验证路径。</p><div class="chips"><span>全部文章</span><span>基础设施</span><span>安全审计</span><span>自动化</span></div></div></section><section class="section"><div class="container research-list">${cards}</div></section></main>`));
const latest=records.slice(0,3).map(r=>`<article><p class="eyebrow">${categoryLabel[r.category]}</p><h3><a href="/articles/${r.slug}/">${r.title}</a></h3><p>${r.description}</p><div class="card-meta"><span>Manguo Labs Research</span><time>${formatDate(r.published)}</time><span>预计阅读 ${r.minutes} 分钟</span></div></article>`).join('');
write('index.html',document({title:'Manguo Labs｜数字产品与技术解决方案',description:'Manguo Labs 提供线路高可用、XBoard 订阅安全审计、节点扩展与采集等数字产品与技术解决方案。',canonical:'https://manguolabs.com/',extra:'<script type="application/ld+json">{"@context":"https://schema.org","@type":"Organization","name":"Manguo Labs","url":"https://manguolabs.com/","sameAs":["https://t.me/ManguoShop_bot"]}</script>'},`<main><section class="home-hero"><div class="container hero-grid"><div><p class="eyebrow">Manguo Labs</p><p class="hero-kicker">基础设施 · 安全审计 · 自动化</p><h1>为复杂的技术运营问题，<em>构建可靠、可验证的解决方案。</em></h1><p class="lead">围绕线路高可用、XBoard 安全审计与节点自动化，把重复问题沉淀成可长期运行的系统。</p><div class="actions"><a class="btn primary" href="#solutions">探索解决方案</a><a class="btn" href="/articles/">阅读技术研究</a></div></div><div class="topology" aria-label="抽象技术拓扑"><span class="topo-label">系统状态 / 已验证</span><i class="node n1"></i><i class="node n2"></i><i class="node n3"></i><i class="node n4"></i><b class="line l1"></b><b class="line l2"></b><b class="line l3"></b><div class="topo-core">ML<span>01</span></div></div></div></section><section class="section capabilities"><div class="container"><div class="section-title"><p class="eyebrow">核心能力</p><h2>在压力之下，依然让系统清晰、可控。</h2></div><div class="cap-grid"><article class="infra">${icon('infra')}<h3>基础设施</h3><p>围绕真实链路设计可靠、可维护的交付架构。</p></article><article class="security">${icon('security')}<h3>安全审计</h3><p>以证据为中心的评估，并为人工复核保留空间。</p></article><article class="automation">${icon('automation')}<h3>自动化</h3><p>用受控工作流把重复操作沉淀为可靠系统。</p></article></div></div></section><section id="solutions" class="section surface"><div class="container"><div class="section-title"><p class="eyebrow">解决方案</p><h2>从真实运营约束出发，设计技术工作。</h2></div><div class="solution-cards">${solutions.map(s=>`<article class="${s.key}"><div class="icon-frame">${icon(s.key)}</div><p class="eyebrow">${s.label}</p><h3>${s.title}</h3><p>${s.summary}</p><div class="tags"><span>${s.key==='security'?'证据分析':s.key==='infra'?'链路架构':'运营自动化'}</span><span>${s.key==='security'?'人工复核':s.key==='infra'?'风险隔离':'安全下发'}</span></div><a class="text-link" href="/${s.path}/">查看详情 <span>→</span></a></article>`).join('')}</div></div></section><section class="section"><div class="container"><div class="section-title row"><div><p class="eyebrow">最新技术文章</p><h2>来自真实现场的技术笔记。</h2></div><a class="text-link" href="/articles/">全部文章 <span>→</span></a></div><div class="latest-grid">${latest}</div></div></section><section class="section method"><div class="container"><p class="eyebrow">我们如何解决问题</p><h2>发现问题，建立证据，设计架构，验证方案，持续优化。</h2><ol><li>发现问题</li><li>建立证据</li><li>设计架构</li><li>验证方案</li><li>持续优化</li></ol></div></section><section class="contact-band"><div class="container"><p class="eyebrow">Manguo Labs</p><h2>从你现有的系统开始。</h2><a class="btn light" href="https://t.me/ManguoShop_bot">联系我们</a></div></section></main>`));
