#!/usr/bin/env node
import fs from 'node:fs'; import path from 'node:path';
const fail=[], read=p=>fs.readFileSync(p,'utf8'), exists=p=>fs.existsSync(p);
const articles=fs.readdirSync('articles',{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>`articles/${x.name}/index.html`).filter(exists).sort();
const pages=['index.html','articles/index.html','node-firewall/index.html','xboard-security-audit/index.html','xboard-node-extension/index.html',...articles];
for(const file of pages){const html=read(file), h1=(html.match(/<h1\b/gi)||[]).length;if(h1!==1)fail.push(`${file}: expected one H1, got ${h1}`);for(const p of [/<title>[^<]{8,}<\/title>/i,/<meta name="description" content="[^"]{20,}"/i,/<meta name="robots"/i,/<link rel="canonical" href="([^"]+)"/i])if(!p.test(html))fail.push(`${file}: missing SEO metadata`);const expected=`https://manguolabs.com/${file==='index.html'?'':file.replace(/index\.html$/,'')}`,canonical=html.match(/<link rel="canonical" href="([^"]+)"/i)?.[1];if(canonical&&canonical!==expected)fail.push(`${file}: canonical mismatch`);for(const m of html.matchAll(/href="([^"]+)"/g)){const link=m[1];if(!link.startsWith('/')||link.startsWith('//'))continue;const clean=link.split(/[?#]/)[0];if(!clean||clean.startsWith('/assets/'))continue;const target=clean.endsWith('/')?`${clean.slice(1)}index.html`:clean.slice(1);if(!exists(target))fail.push(`${file}: broken link ${link}`)}}
const commercialMappings={'articles/node-ip-blocked/index.html':'/node-firewall/','articles/transit-ip-blocked/index.html':'/node-firewall/','articles/reality-node-blocked/index.html':'/node-firewall/','articles/xboard-token-multi-ip/index.html':'/xboard-security-audit/','articles/xboard-free-node-collector/index.html':'/xboard-node-extension/'};
for(const [file,servicePath] of Object.entries(commercialMappings)){const html=read(file),body=html.match(/<article\b[\s\S]*?<\/article>/i)?.[0]||'';if(!body.includes('Manguo Labs'))fail.push(`${file}: BRAND_CONTEXT failed`);if(!body.includes(`href="${servicePath}"`))fail.push(`${file}: PRODUCT_LINK failed for ${servicePath}`);if(!/(什么时候|超出|无法区分|反复失效|系统化)/.test(body))fail.push(`${file}: SERVICE_ALIGNMENT transition failed`);if(!html.includes('class="btn primary" href="https://t.me/ManguoShop_bot"'))fail.push(`${file}: COMMERCIAL_CTA failed`);if((html.match(/class="btn primary" href="https:\/\/t\.me\/ManguoShop_bot"/g)||[]).length!==1)fail.push(`${file}: expected one primary Telegram CTA`)}
for(const file of articles){const html=read(file);for(const phrase of ['100%解决','永不被墙','永久不封'])if(html.includes(phrase))fail.push(`${file}: forbidden absolute promise ${phrase}`)}
const sitemap=read('sitemap.xml');if(!/<urlset xmlns="http:\/\/www\.sitemaps\.org\/schemas\/sitemap\/0\.9">/.test(sitemap))fail.push('sitemap.xml: invalid namespace');const urls=[...sitemap.matchAll(/<loc>(https:\/\/manguolabs\.com\/[^<]*)<\/loc>/g)].map(m=>m[1]);for(const url of urls){const rel=url.slice('https://manguolabs.com/'.length),target=rel?`${rel.replace(/\/$/,'')}/index.html`:'index.html';if(!exists(target))fail.push(`sitemap missing page: ${url}`)}for(const file of articles){const rel=file.replace(/index\.html$/,''),url=`https://manguolabs.com/${rel}`;if(!urls.includes(url))fail.push(`${file}: absent from sitemap`);if(!read('articles/index.html').includes(`/${rel}`))fail.push(`${file}: absent from articles index`)}
function walk(dir='.'){for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(p.startsWith('.git'))continue;if(e.isDirectory())walk(p);else if(/(^|\/)(\.DS_Store|\._[^/]+|MANIFEST\.sha256|\.env(?:\..*)?|[^/]+\.(?:pem|key|sql|sqlite))$/.test(p))fail.push(`forbidden file: ${p}`)}}walk();if(fail.length){console.error(fail.join('\n'));process.exit(1)}console.log(`SEO validation passed: ${pages.length} pages, ${urls.length} sitemap URLs`);
